### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by FredericoAndrade** [LibraryOfCongress/bagger-js#41]

**Comment by acdha** [comment]
It's always been an experiment rather than a production tool. I was talking with @dbrunton about changing that but it's a question of resources. We have to fix some undocumented AWS API changes which broke the CORS setup but that shouldn't be an insurmountable challenge.

Are you interested in contributing to it?

**Comment by acdha** [comment]
As of the last couple weeks this is again capable of generating valid bags and the core UI is considerably more fleshed out. I’m closing this issue now; Amy specific issues can be opened separately.
